import "./globals.css";
import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./components/Provider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
<<<<<<< HEAD
  params?: { lang: string };
}) {
  const lang = params?.lang || "en"


=======
}) {
>>>>>>> 6d05bfaae1f9f4e516acd686cb830eb7965be7ed
  return (
    <html lang="en" dir="ltr">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

